### PR TITLE
Accept an AST and a whitelist Array of AST leaves

### PR DESCRIPTION
**Pull request by kemitchell**
Taking off from: https://github.com/jslicense/spdx-satisfies.js/pull/7#issuecomment-476014048

This PR redesigns the external API to take new kinds of arguments:

1. the AST for an SPDX expression, in the form returned by [spdx-expression-parse](https://www.npmjs.com/package/spdx-expression-parse)

2. an Array of AST leaves, each corresponding to a license, license with exception, license range, or license range with exception

A few benefits:

- This approach massively simplifies the underlying algorithm.  We're back to straightforward recursion.

- This approach leaves room for nonstandard license identifiers. `spdx-expression-parse` is now a `devDependency`, for the test suite.  But neither the parser nor the license-list data package it depends on remain production dependencies.

- Completely valid and completely unanswerable questions about the intended semantics are entirely avoided. Which is a good sign.

### CODE REVIEW

**Comment by kemitchell** [comment]
Paging @jeffmcaffer.

**Comment by jeffmcaffer** [comment]
@kemitchell this looks much simpler and has lots of great attributes. Love that the recursion logic follows exactly the same logic as the expression itself. The understanding that in the end we are just matching against a set of licenses rather than another expression that enables this. 

Would love to stew on this for a day (or get @dabutvin so stew) to see if there are any gotchas.

**Comment by kemitchell** [comment]
@jeffmcaffer I sent you an invite to the org. Hack responsibly!

**Comment by jeffmcaffer** [comment]
Hah! Achievement unlocked!

**Comment by kemitchell** [comment]
@jeffmcaffer any objection to my going ahead and releasing as semver-major? Alternatively, I’d you have strong reservations, I can fork and rename to meet my own immediate needs, and we can discuss reconciling when you have time.

**Comment by kemitchell** [comment]
Closing this in deference to #17.

**Pull request closed without merging**
