### PR TITLE
handle unordered licenses using an expand/flatten approach

### LINKED ISSUE #9: order matters unexpectedly
The following examples fail only because the license ordering is different. That is unexpected

```js 
assert(satisfies('MIT AND GPL-2.0 AND ISC', 'ISC AND GPL-2.0 AND MIT'))
assert(satisfies('MIT AND ISC', '(ISC AND MIT) OR (GPL-2.0 AND ISC)'))
```

Related, I'm curious about the api intention here. Can you express in words how a user of the API should be thinking about the answer? For example, 

* if the user asks "If I accept MIT, is MIT AND ISC ok?" that should be no.

Does order of the arguments matter? A satisfying B does not necessarily imply the inverse.

### PR DESCRIPTION
**Pull request by jeffmcaffer**
Fixes #9 

Allows unordered license expressions to satisfy one another. That is, `satisfies('MIT AND ISC', 'ISC AND MIT')` should be true. 

The approach taken is to expand the first expression into a collection of disjuncted conjunctions (e.g., `(MIT OR ISC) AND GPL-3.0` expands to `[[GPL-3.0 AND MIT], [ISC AND MIT]]`) and flattened the second argument to capture all mentioned licenses. 

Then we see if at least one of the OR clauses from the first arg has all its licenses compatible in the flattened second arg.

### CODE REVIEW

**Comment by jeffmcaffer** [comment]
I see the tests failed because of the use of spread operators. If you like the direction this is going, I can update the code code to use alternate mechanisms.

**Review by kemitchell — CHANGES_REQUESTED** [review]
@jeffmcaffer, this looks like good work!

However, we do want to keep this package running on old (ancient) versions of Node, on which, it turns out, a lot of the folks who have to do enterprise-class license audit are stuck.

If it's all still fresh in mind for you, might you...?:

1. [ ] refactor onto ES5
2. [ ] drop the edit to `package.json`

I think you're correct that this will be SemVer-major, but I want to keep versioning consistent with how we've done past releases.

**Comment by jeffmcaffer** [comment]
Will do. It's been so long since doing ES5 I'll have to lookup what's in/out :-) but I completely get the requirement. No problem.

For the package version, what do you want to see change there? 4.0.2? 4.1.0?  On reflection I'm not sure this is an API change or a "bug fix". That order matters was not part of the API, just the way the code worked. A caller of the API (like me) would have expected it ignore order as there is nothing order-related in the SPDX spec (AFAIK).

**Comment by kemitchell** [comment]
@jeffmcaffer, if you'd prefer I do it, let me know, and give me edit perms on the PR.

**Comment by kemitchell** [comment]
@jeffmcaffer, don't touch package.json in the PR. We can handle from `master` in a release-specific commit. See, e.g., edbc31121e5da4fc3fb47172cc6b369ab6603ccd

**Comment by kemitchell** [comment]
@jeffmcaffer Want to add yourself to `contributors` in `package.json`?

**Pull request merged**
